/**
 * pages/index.js — AI Image Detector
 * Main landing page & application shell.
 */

import { useState, useCallback } from 'react';
import Head from 'next/head';
import ImageUploader from '../components/ImageUploader';
import ResultCard from '../components/ResultCard';
import styles from '../styles/Home.module.css';

// ── Animated Loading Dots ─────────────────────────────────────────────────
function LoadingState() {
  return (
    <div className={styles.loadingWrap}>
      <div className={styles.loadingOrb}>
        <div className={styles.orbCore} />
        <div className={styles.orbRing1} />
        <div className={styles.orbRing2} />
        <div className={styles.orbRing3} />
      </div>
      <p className={styles.loadingTitle}>Analysing image</p>
      <p className={styles.loadingSubtitle}>
        Scanning pixel patterns with neural vision…
      </p>
      <div className={styles.loadingDots}>
        <span />
        <span />
        <span />
      </div>
    </div>
  );
}

// ── Stat Badge ────────────────────────────────────────────────────────────
function StatBadge({ value, label }) {
  return (
    <div className={styles.statBadge}>
      <span className={styles.statValue}>{value}</span>
      <span className={styles.statLabel}>{label}</span>
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────
export default function Home() {
  const [selectedImage, setSelectedImage] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Reset result when a new image is selected
  const handleImageSelect = useCallback((img) => {
    setSelectedImage(img);
    setResult(null);
    setError(null);
  }, []);

  // Analyse the uploaded image
  const handleAnalyse = async () => {
    if (!selectedImage) return;
    setLoading(true);
    setResult(null);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('image', selectedImage.file);

      const res = await fetch('/api/detect-image', {
        method: 'POST',
        body: formData,
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Something went wrong. Please try again.');
      }

      setResult(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setSelectedImage(null);
    setResult(null);
    setError(null);
  };

  return (
    <>
      <Head>
        <title>AI Image Detector — Real vs Synthetic</title>
        <meta
          name="description"
          content="Detect whether any image was generated by AI or captured by a real camera using state-of-the-art computer vision."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.page}>
        {/* ── Background grid ── */}
        <div className={styles.bgGrid} aria-hidden />

        {/* ── Header ── */}
        <header className={styles.header}>
          <div className={styles.logo}>
            <div className={styles.logoMark}>
              <svg viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="14" cy="14" r="13" stroke="url(#g1)" strokeWidth="1.5" />
                <circle cx="14" cy="14" r="7" fill="url(#g2)" opacity="0.8" />
                <circle cx="14" cy="14" r="3" fill="white" opacity="0.95" />
                <defs>
                  <linearGradient id="g1" x1="0" y1="0" x2="28" y2="28" gradientUnits="userSpaceOnUse">
                    <stop stopColor="#6366f1" />
                    <stop offset="1" stopColor="#22d3ee" />
                  </linearGradient>
                  <radialGradient id="g2" cx="0.5" cy="0.5" r="0.5">
                    <stop stopColor="#6366f1" />
                    <stop offset="1" stopColor="#22d3ee" />
                  </radialGradient>
                </defs>
              </svg>
            </div>
            <span className={styles.logoText}>Detektiv</span>
          </div>

          <nav className={styles.nav}>
            <a href="https://huggingface.co" target="_blank" rel="noopener noreferrer" className={styles.navLink}>
              Model
            </a>
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" className={styles.navLink}>
              GitHub
            </a>
          </nav>
        </header>

        {/* ── Hero ── */}
        <section className={styles.hero}>
          <div className={styles.heroEyebrow}>
            <span className={styles.eyebrowDot} />
            <span>Powered by Hugging Face Vision AI</span>
          </div>

          <h1 className={styles.heroTitle}>
            <span className={styles.titleLine1}>AI Image</span>
            <span className={styles.titleLine2}>Detector</span>
          </h1>

          <p className={styles.heroSubtitle}>
            Upload any image and instantly find out whether it was crafted by
            an AI model or captured through a real camera lens.
          </p>

          <div className={styles.stats}>
            <StatBadge value="99ms" label="Avg. response" />
            <div className={styles.statDivider} />
            <StatBadge value="ViT" label="Vision model" />
            <div className={styles.statDivider} />
            <StatBadge value="10MB" label="Max file size" />
          </div>
        </section>

        {/* ── App Card ── */}
        <main className={styles.appCard}>
          <div className={styles.cardInner}>
            {/* ── Uploader ── */}
            <section className={styles.uploaderSection}>
              <div className={styles.sectionLabel}>
                <span className={styles.sectionNum}>01</span>
                <span>Upload Image</span>
              </div>

              <ImageUploader
                onImageSelect={handleImageSelect}
                selectedImage={selectedImage}
                disabled={loading}
              />

              {/* Action Buttons */}
              <div className={styles.actions}>
                <button
                  className={styles.analyseBtn}
                  onClick={handleAnalyse}
                  disabled={!selectedImage || loading}
                >
                  {loading ? (
                    <>
                      <span className={styles.btnSpinner} />
                      Analysing…
                    </>
                  ) : (
                    <>
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                      </svg>
                      Analyse Image
                    </>
                  )}
                </button>

                {(selectedImage || result) && (
                  <button className={styles.resetBtn} onClick={handleReset} disabled={loading}>
                    Reset
                  </button>
                )}
              </div>
            </section>

            {/* ── Divider ── */}
            <div className={styles.panelDivider} />

            {/* ── Result Panel ── */}
            <section className={styles.resultSection}>
              <div className={styles.sectionLabel}>
                <span className={styles.sectionNum}>02</span>
                <span>Detection Result</span>
              </div>

              {loading && <LoadingState />}

              {!loading && result && <ResultCard result={result} />}

              {!loading && error && (
                <div className={styles.errorCard} role="alert">
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <circle cx="12" cy="12" r="10" />
                    <line x1="12" y1="8" x2="12" y2="12" />
                    <line x1="12" y1="16" x2="12.01" y2="16" />
                  </svg>
                  <div>
                    <p className={styles.errorTitle}>Analysis Failed</p>
                    <p className={styles.errorMsg}>{error}</p>
                  </div>
                </div>
              )}

              {!loading && !result && !error && (
                <div className={styles.emptyResult}>
                  <div className={styles.emptyResultIcon}>
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2">
                      <rect x="3" y="3" width="18" height="18" rx="4" />
                      <circle cx="8.5" cy="8.5" r="1.5" />
                      <polyline points="21 15 16 10 5 21" />
                    </svg>
                  </div>
                  <p className={styles.emptyResultText}>
                    Your detection result will appear here after analysis.
                  </p>
                </div>
              )}
            </section>
          </div>
        </main>

        {/* ── How it works ── */}
        <section className={styles.howItWorks}>
          <h2 className={styles.howTitle}>How It Works</h2>
          <div className={styles.steps}>
            {[
              { n: '01', title: 'Upload', desc: 'Drop any JPG, PNG or WebP image into the uploader.' },
              { n: '02', title: 'Analyse', desc: 'Your image is sent to a ViT model fine-tuned for synthetic detection.' },
              { n: '03', title: 'Result', desc: 'Receive a prediction with a confidence score in under a second.' },
            ].map((s) => (
              <div key={s.n} className={styles.step}>
                <span className={styles.stepNum}>{s.n}</span>
                <h3 className={styles.stepTitle}>{s.title}</h3>
                <p className={styles.stepDesc}>{s.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── Footer ── */}
        <footer className={styles.footer}>
          <p>
            Built with{' '}
            <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">
              Next.js
            </a>{' '}
            &amp;{' '}
            <a href="https://huggingface.co" target="_blank" rel="noopener noreferrer">
              Hugging Face
            </a>
            . Open source.
          </p>
        </footer>
      </div>
    </>
  );
}
